### ISSUE TITLE
BUG: hideScrollBars: true

### ISSUE THREAD

**Issue by ChandlerMBing** [cmswalker/fullpage-react#78] opened 2018-03-20 15:05 UTC
Setting hideScrollBars to true disables scrolling completely.

I'm using up-to-date chrome on OSX. I have a fixed position nav and am using react-router v4.x if that helps.

**Comment by cmswalker** [comment] 2018-03-25 17:30
I was unable to reproduce this however I did find a bug where vertical scroll bars are showing on horizontal slides. Could you give an example?

**Comment by cmswalker** [comment] 2018-03-28 17:52
Fixed in `3.0.30`

**Closed by cmswalker** 2018-03-28 17:52 UTC
Labels: Acknowledged, bug

**Comment by kpoddubnyi** [comment] 2018-06-27 12:36
@cmswalker Hey!

Faced the same issue. I'm not able to scroll to the next section in Chrome, Firefox (OSX). When I delete a `overflow: hidden` property from html or body it starts working good.

Btw, in Safari it changes slides but it works strange - every scroll provokes jump to the first section and then scroll to the next
